/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/bills/{billId}/shares": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Positive integer id of the bill. */
                billId: components["parameters"]["BillId"];
            };
            cookie?: never;
        };
        /** Get the people and their percentages for a bill. */
        get: operations["getBillShares"];
        /** Replace the full set of shares for a bill. */
        put: operations["replaceBillShares"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Bill: {
            /** Format: int64 */
            id: number;
            description: string;
            /**
             * Format: int64
             * @description Total amount of the bill, in cents.
             */
            totalCents: number;
        };
        Share: {
            /** Format: int64 */
            id: number;
            name: string;
            /**
             * Format: int32
             * @description Percentage in basis points (10000 = 100.00%).
             */
            percentageBasisPoints: number;
            /**
             * Format: int64
             * @description This share's amount of the bill, in cents.
             */
            amountCents: number;
        };
        BillSharesResponse: {
            bill: components["schemas"]["Bill"];
            shares: components["schemas"]["Share"][];
            /**
             * Format: int32
             * @description Sum of all shares' percentageBasisPoints.
             */
            totalBasisPoints: number;
        };
        ShareInput: {
            name: string;
            /** Format: int32 */
            percentageBasisPoints: number;
        };
        ReplaceSharesRequest: {
            shares: components["schemas"]["ShareInput"][];
        };
        /** @enum {string} */
        ErrorCode: "VALIDATION_ERROR" | "BAD_REQUEST" | "NOT_FOUND" | "UNAUTHORIZED" | "INTERNAL_ERROR";
        FieldError: {
            /** @description Dotted/indexed path to the offending field, e.g. "shares[2].percentageBasisPoints". */
            field: string;
            message: string;
        };
        ErrorResponse: {
            code: components["schemas"]["ErrorCode"];
            message: string;
            details?: components["schemas"]["FieldError"][];
            requestId: string;
        };
    };
    responses: {
        /** @description The request was malformed (invalid JSON, invalid path parameter, unknown fields). */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The bill does not exist. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description The request failed validation (e.g. percentages don't sum to 100.00). */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description An unexpected error occurred. */
        InternalError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description Positive integer id of the bill. */
        BillId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getBillShares: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Positive integer id of the bill. */
                billId: components["parameters"]["BillId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The bill's shares. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillSharesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
    replaceBillShares: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Positive integer id of the bill. */
                billId: components["parameters"]["BillId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceSharesRequest"];
            };
        };
        responses: {
            /** @description The bill's shares, as saved. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BillSharesResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            404: components["responses"]["NotFound"];
            422: components["responses"]["ValidationError"];
            500: components["responses"]["InternalError"];
        };
    };
}
